[package]
name = "eskom-calendar-api"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-runtime = "0.15.0"
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
shuttle-rocket = "0.15.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.28.0", features = ["full"] }
chrono = "0.4.19"
csv = "1.1"
